/*
Create ISDB SQL Tables
2-17-19
*/

CREATE DATABASE isdb;
USE isdb;

CREATE TABLE User (
	username VARCHAR(32) NOT NULL PRIMARY KEY,
	password VARCHAR(32) NOT NULL
);

CREATE TABLE Song (
	sid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	relDate VARCHAR(32)
);

CREATE TABLE Artist (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL
);

CREATE TABLE Album (
	aid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL,
	relDate VARCHAR(32),
	numTracks INT
);

CREATE TABLE SongAlbum (
	sid INT NOT NULL,
	aid INT NOT NULL,
	PRIMARY KEY (sid, aid),
	FOREIGN KEY(sid) REFERENCES Song(sid),
	FOREIGN KEY(aid) REFERENCES Album(aid)
);

CREATE TABLE SongArt (
	sid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (sid, id),
	FOREIGN KEY(sid) REFERENCES Song(sid),
	FOREIGN KEY(id) REFERENCES Artist(id)
);

CREATE TABLE AlbumArt (
	aid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (aid, id),
	FOREIGN KEY(aid) REFERENCES Album(aid),
	FOREIGN KEY(id) REFERENCES Artist(aid)
);
